apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gyeongdodot-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/leestana01/gitops
    targetRevision: HEAD
    path: gyeongdodot/apps/gyeongdodot-infra/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: gyeongdodot

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
