apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gyeongdodot-dev-front
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/team-CtrlG/gitops
    targetRevision: HEAD
    path: apps/gyeongdodot-front/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: gyeongdodot-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
